% 1 wm  = 2,wc = 1.2wm,Ts = 1;
wm = 2;
wc = 1.2*wm;
Ts = 1;
ws = 2*pi/Ts;
n = -100:100;
nTs = n*Ts;
f = 0.5*(1+cos(nTs)).*(Heaviside(nTs+pi)-Heaviside(nTs-pi));
Dt = 0.005; t = -15:Dt:15;
fa = f*Ts*wc/pi*sinc((wc/pi)*(ones(length(nTs),1)*t-nTs'*ones(1,length(t))));
t1 = -15:0.5:15;
f1 = 0.5*(1+cos(t1)).*(Heaviside(t1+pi)-Heaviside(t1-pi));
subplot(311); stem(t1,f1); 
xlabel('kTs');ylabel('kTs');title('sa(t) = sinc(t/pi) 的采样信号');
subplot(312); plot(t,fa);
xlabel('t'); ylabel('fa(t)');title('由sa(t) = sinc(t/pi)临界采样信号重构sa(t) ');
grid ;
error = abs(fa - 0.5*(1+cos(t)).*(Heaviside(t+pi)-Heaviside(t-pi)));
subplot(313);plot(t,error); xlabel('t');ylabel('error(t)'); 
title('采样信号与原信号的误差error(t)');


% 2 wm = 2,wc = 2,Ts = 2.5;
wm = 2;
wc = 2;
Ts = 2.5;
ws = 2*pi/Ts;
n = -100:100;
nTs = n*Ts;
f = 0.5*(1+cos(nTs)).*(Heaviside(nTs+pi)-Heaviside(nTs-pi));
Dt = 0.005; t = -15:Dt:15;
fa = f*Ts*wc/pi*sinc((wc/pi)*(ones(length(nTs),1)*t-nTs'*ones(1,length(t))));
t1 = -15:0.5:15;
f1 = 0.5*(1+cos(t1)).*(Heaviside(t1+pi)-Heaviside(t1-pi));
subplot(311); stem(t1,f1); 
xlabel('kTs');ylabel('kTs');title('sa(t) = sinc(t/pi) 的采样信号');
subplot(312); plot(t,fa);
xlabel('t'); ylabel('fa(t)');title('由sa(t) = sinc(t/pi)临界采样信号重构sa(t) ');
grid ;
error = abs(fa - 0.5*(1+cos(t)).*(Heaviside(t+pi)-Heaviside(t-pi)));
subplot(313);plot(t,error); xlabel('t');ylabel('error(t)'); 
title('采样信号与原信号的误差error(t)');
